export enum FieldTypes {
    TextArea = 1,
    FieldString = 2,
    FieldEmail = 3,
    FieldDecimal = 4,
    FieldInteger = 5,
    FieldMobileNumber = 6,
    Checkbox = 7,
    Date = 8,
    Time = 9,
    DateTime = 10,
    DropDown = 11,
    SingleChoice = 12,
    MultipleChoice = 13,
    Boolean = 14,
    Rate = 15,
    Counter = 16,
    ImagePicker = 17,
    VideoPicker = 18,
    Seekbar = 19,
    Signature = 20,
    LinkButton = 21
}